### ISSUE TITLE
Question: How to assign tilesheet properties to wall sprites?

### ISSUE THREAD

**Issue by davidjtferguson** [dganzella/chickenTiledLoader#2]
I have a tile set with several properties - solid, sandPit, etc.

I've adapted the code in the demo you provide with the level 1-1 example code to assign a property to all the wall sprites for collision.
How can I match up the properties of a tileset tile to the sprite that ends up being created from it?

```
    ---creating collision for floor

    local tileGidsThatAreGrounds = {}

    for i = 1, #tmjloader.tileset.tiles do
        local tile = tmjloader.tileset.tiles[i]

        local properties = tmjloader:getPropsOfTile(tile)

        if properties.sandPit then
            print("sandpit found") -- how to assign to sprites?
        end

        if properties.solid == true then
            if not arrContains(tileGidsThatAreGrounds, tile.id + 1) then
                table.insert(tileGidsThatAreGrounds, tile.id + 1)
            end
        end
    end

    local tileGidsThatAreNotGrounds = {}

    for i = 1, tmjloader.tileset.tilecount do
        if not arrContains(tileGidsThatAreGrounds, i) then
            table.insert(tileGidsThatAreNotGrounds, i)
        end
    end

    print(tileGidsThatAreNotGrounds[1])

    local walls = gfx.sprite.addWallSprites(tmjloader.tileMapsByLayer['floor'], tileGidsThatAreNotGrounds)

    -- Set properties for wall tiles
    for i = 1, #walls do
		local w = walls[i]
		w.isWall = true

                -- if the sprite's tile has property sandPit == true, add to sprite here...?
               -- How would I figure this out?
	end
```

And collision later in my avatar class...

```
        self.position.x, self.position.y, collisions, collisionsCount = self:moveWithCollisions(self.position)
        
        self.onGround = false

        for i = 1, collisionsCount do
            
            local c = collisions[i]

            if c.other.sandPit == true then
                -- How to assign this property so I can check against it here?
            end

            if c.other.isWall == true then -- this works
                ...
```

Any suggestions will be appreciated - I'm unclear as to if the library supports this somehow or if I should be building my own logic to figure it out.

Thanks!

**Comment by dganzella** [comment]
Oh, you are skipping a trillion steps.

First of all, I just pushed a fix to the getGidAtLayerPos method, you will need to pick the updated version.

---

You see, in the example, we loop ```tmjloader.tileset.tiles```  properties, which happens to be just a list of the tiles with special properties -- we are not looping the tileset in XY and asking every XY position if that position has anything special.

That's because the function ```gfx.sprite.addWallSprites``` does a trillion things, its a convenient function, but inside it an unholy amount of things are happening, including the creation of sprites.

You also pass the tilemap itself to the function (that maps XY -> gid), so that is how its able to create the collisions in the proper positions.

------

In your situation, you wanna now create special sprites at special XY positions, so we need to loop the X and Y of the tileset. 
the code looks like this

```
local bg = tmjloader:getLayerByName('floor')

for i = 0, tmjloader.root.width - 1 do
	for j = 0, tmjloader.root.height - 1 do
		local gid = tmjloader:getGidAtLayerPos(i, j, bg)
		if gid ~= nil then
			local properties = tmjloader:getPropsTileOfGid(gid)

			if properties.sandPit then
				local sand = gfx.sprite.new()
				sand:moveTo(i * tmjloader.root.tilewidth, j * tmjloader.root.tileheight)
                                sand:setCollideRect(0,0,tmjloader.root.tilewidth,tmjloader.root.tileheight)
				sand.isSand = true
				sand:add()
			end
		end
	end
end
```
also you probably want to use  kCollisionTypeOverlap rather than kCollisionTypeFreeze between character and the sandpit

**Comment by dganzella** [comment]
![image](https://github.com/user-attachments/assets/5b3f9a57-1237-48dd-9aad-d003ced96908)

I updated the example to add your situation

Be aware that the objects wont be optimized, because if does not goes throught the ```addWallSprites``` special group algorithm.

If you are spawning a lot of sand areas, you probably will want to use a workaround and still use the ```addWallSprites``` method, but you will need to hack it a bit, you will need o pass the gids that are not sand instead that are not ground, and then adjust the created sprites as you need -- like adjusting the collision mask and callback

**Comment by davidjtferguson** [comment]
Ah right okay, that code looks a lot like the code in the level 1-1 example project as well which I was gonna do for npcs etc.
I'm surprised there's no obvious way to get the tile gid from each sprite returned by the  addWallSprites function to know what to add extra properties to after. I want the sandpit to be the same as walls (they have the solid flag currently) but with this extra bool property on it, so it's annoying I can't just do if sprite[i].tileGid == sandPitGid then sprite[i].isSandPit = true. Maybe there is a way to do it and I just missed it, I'll read the docs again tomorrow.
But yeah if this is the done thing it'll be easy enough to do instead.
Thanks for the help! Sounds like it's not really related to the library then, but thank you very much for the example code and updates :D
... Ah, I suppose I could call addWallSprites once for all the walls, then again for all the sandpits?

**Comment by dganzella** [comment]
> Ah right okay, that code looks a lot like the code in the level 1-1 example project as well which I was gonna do for npcs etc.
> I'm surprised there's no obvious way to get the tile gid from each sprite returned by the  addWallSprites function to know what to add extra properties to after. I want the sandpit to be the same as walls (they have the solid flag currently) but with this extra bool property on it, so it's annoying I can't just do if sprite[i].tileGid == sandPitGid then sprite[i].isSandPit = true. Maybe there is a way to do it and I just missed it, I'll read the docs again tomorrow.
> But yeah if this is the done thing it'll be easy enough to do instead.
> Thanks for the help! Sounds like it's not really related to the library then, but thank you very much for the example code and updates :D
> ... Ah, I suppose I could call addWallSprites once for all the walls, then again for all the sandpits?
> 

there is no way to get gid for each sprite in addWallSpeites because it does not make sense.

a sprite added by addwall sprites is not a visual sprite, its just a collision.

and the collision sprites may take more than 1 tile size, thats the very objective of add wall sprites, to make as few collision sprites as possible.

anyway, you can yes, call  addWallSprites for walls and then call for sandpits!

but these are just the collisions!!! and their shape may vary wildly!

![Image-1-18.png](https://github.com/user-attachments/assets/63bf666d-d240-4672-831b-7677902e6eb7)

it uses a minimun islands algorithm

the images themselves are being added somewhere else in the code!!! when we create the tilemap sprites

**Comment by davidjtferguson** [comment]
Aaah, okay. Thank you. I didn't realise the addWallSprites was grouped together shapes for collision, I thought it was a sprite for each tile with the image. I think in my head a 'sprite' is always a visual thing, but I guess I got to drop that idea.

I have this now:
```
    local tileGidsThatAreGrounds = {}
    local tileGidsThatAreSandPits = {}

    for i = 1, #tmjloader.tileset.tiles do
        local tile = tmjloader.tileset.tiles[i]

        local properties = tmjloader:getPropsOfTile(tile)

        if properties.solid == true then
            if not arrContains(tileGidsThatAreGrounds, tile.id + 1) then
                table.insert(tileGidsThatAreGrounds, tile.id + 1)
            end
        end
        
        if properties.sandPit then
            if not arrContains(tileGidsThatAreSandPits, tile.id + 1) then
                table.insert(tileGidsThatAreSandPits, tile.id + 1)
            end
        end
    end

    local tileGidsThatAreNotGrounds = {}

    for i = 1, tmjloader.tileset.tilecount do
        if not arrContains(tileGidsThatAreGrounds, i) then
            table.insert(tileGidsThatAreNotGrounds, i)
        end
    end

    local walls = gfx.sprite.addWallSprites(tmjloader.tileMapsByLayer['floor'], tileGidsThatAreNotGrounds)

    -- Set properties for wall tiles
    for i = 1, #walls do
		local w = walls[i]
		w.isWall = true
	end

    local tileGidsThatAreNotSandPits = {}

    for i = 1, tmjloader.tileset.tilecount do
        if not arrContains(tileGidsThatAreSandPits, i) then
            table.insert(tileGidsThatAreNotSandPits, i)
        end
    end

    local walls = gfx.sprite.addWallSprites(tmjloader.tileMapsByLayer['floor'], tileGidsThatAreNotSandPits)

    -- Set properties for sand pit tiles
    for i = 1, #walls do
		local w = walls[i]
		w.isWall = true
                w.isSandPit = true
	end
```

It's verbose, but you get the idea.
And if I wanted to do anything more complicated (e.g. have an animated sprite) I'd need to find it and create a sprite with the extra data just for that tile as you described.
Thank you very much for your explenations!
